- api/src/data_inclusion/api/entrypoints/fastapi.py
- api/src/data_inclusion/api/schema.py
- api/tests/inclusion/test_api.py
format de réponse pour endpoint `/api/search/services` change en :
```json
[
{
"service": {
...
"structure" : { ... }
...
},
"distance": 40,
},
...
]
```
* `distance` n'est plus dans le service
* la structure est sérialisée dans le service
> feat(api): nest structure in search results

- docker-compose.yml
docker-compose up returns "contains true, which is an invalid type, it should be a string, number, or a null" in version 1.29.2.
The spec says :
https://github.com/compose-spec/compose-spec/blob/master/spec.md#environment
And indeed, in the map version (not the list in key=value) for the YAML properties, the `True` value must be quoted.
I don't really understand how it worked before, but maybe was it just a warning.
> chore(root) : Fix docker-compose base environment values

- pipeline/dbt/models/staging/sources/dora/_dora__models.yml
The column is not required in the DORA datascheme in the database nor is enforced to be non null in the DORA API that exports the data to us.
Moreover, the 'frais' are also not mandatory in data-inclusion-schema, so everything points in the direction of the constraint to be lifted.
Cf. #141
> fix(pipeline): Do not require 'frais' to be not null

- pipeline/dags/dag_utils/settings.py
- pipeline/src/data_inclusion/scripts/tasks/un_jeune_une_solution.py
- pipeline/src/data_inclusion/scripts/tasks/utils.py
Le dernier commit introduit en #169 ajoute deux fois le nom de l'endpoint, ce qui finit en 404.
De plus les settings continuent de crasher dans les tests de DAGs car le `rstrip` ne fait pas de check préliminaire.
Ceci permet à la fois de re-simplifier le load et de corriger les deux soucis d'un coup.
> fix(pipeline) : Stop 1jeune1solution crash

- deployment/main.tf
The command was ignored since for some reason, and contrary to what the documentation indicates
(https://docs.docker.com/reference/cli/docker/image/prune/#filter)
... we can't use *any* Go duration string. "7d" is invalid.
Replace it with the hour-based version, which works.
> fix(deployment) : Make the image and container prune work

- api/entrypoint.sh
This was removed last week, but still is required.
> fix(api): ensure valid db url scheme

- pipeline/dags/dag_utils/dbt.py
monenfant extraction is not managed using the sources config anymore. Therefore its dbt models are not picked up automatically.
> chore(pipeline): run monenfant models

- api/src/data_inclusion/api/inclusion_data/routes.py
- api/tests/e2e/api/test_inclusion_data.py
We switch to new terms & conditions.
Attendre qu'on switche coté emplois, cf https://github.com/gip-inclusion/les-emplois/pull/4141
> chore(api) : Remove the now useless "proxy" to a given service

- pipeline/dags/import_sources.py
- pipeline/tests/integration/test_geocoding.py
The snapshot task is not connected to all extract task groups.
> chore(pipeline): run snapshot after all extracts

- deployment/main.tf
We frequently encounter disk space issues.
Last I checked, a ton of images were sitting aroung since 5/6 days.
OI don't think we need that much cache time and it seems we don't reuse much of the layers anyway (this could be another investigation, but... longer)
Since every image is always pushed and downloaded almost entirely again, there is little argument that we can just wipe the old ones more frequently.
> chore(deployment) : Reduce the allowed time for images to stay

- deployment/main.tf
It seems reasonable that the Airflow DAGs would access the sources folder and can get object properties in it.
In staging:
```
[2024-08-12T16:08:33.544+0000] {process_utils.py:191} INFO -   File "/opt/airflow/venvs/python/venv/lib/python3.12/site-packages/botocore/client.py", line 1021, in _make_api_call                                  
[2024-08-12T16:08:33.545+0000] {process_utils.py:191} INFO -     raise error_class(parsed_response, operation_name)
[2024-08-12T16:08:33.546+0000] {process_utils.py:191} INFO - botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden                                                 
```
> chore(deployment) : Fix sources object access

- pipeline/dbt/macros/marts_inclusion__unnest_jsonb_list_to_table.sql
Currently, the bridge tables are updated concurrently to the main tables. This can make bridge & main tables inconsistent and hence dbt contracts on fk fail.
> fix(pipeline): bridge tables depend on main tables

- pipeline/dags/notify_rgpd_contacts.py
- pipeline/dbt/models/intermediate/_models.yml
- pipeline/dbt/models/intermediate/int__union__contacts.sql
- pipeline/dbt/models/intermediate/sources/dora/int_dora__contacts.sql
- pipeline/dbt/models/intermediate/sources/mediation_numerique/_mediation_numerique_models.yml
- pipeline/dbt/models/intermediate/sources/mediation_numerique/int_mediation_numerique__contacts.sql
- pipeline/dbt/models/intermediate/sources/mes_aides/_mes_aides__models.yml
- pipeline/dbt/models/intermediate/sources/mes_aides/int_mes_aides__contacts.sql
Vérifié localement que les doublons de la médiation numérique avec Dora, quand l'adresse est la même, ne sont pas notifiés à nouveau (le système fonctionne comme prévu, quoi)
> feat(pipeline) : Send RGPD notifications to mes-aides & mediation-numerique

- pipeline/dags/import_brevo.py
- pipeline/dbt/models/intermediate/brevo/_brevo__models.yml
- pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
Dora ne peut pas construire son étape intermédaire car cette source s'attend à la présence d'une table prevo dans `public_intermediate_tmp` désormais ^^ 
Il faut donc construire les tables Brevo comme les tables sources : dans tmp d'abord, puis testé, puis lancé.
> chore(pipeline) : Corriger l'intégration des contacts Brevo

- pipeline/dags/dag_utils/dbt.py
When introducing the new contacts from mediation_numerique and mes_aides, I did not verify that the "top-level" model was also built.
> chore(pipeline) : Add the int__union__contacts build step

- pipeline/dags/dag_utils/sources/france_travail.py
- pipeline/dbt/models/intermediate/sources/emplois_de_linclusion/int_emplois_de_linclusion__structures.sql
- pipeline/dbt/models/intermediate/sources/mediation_numerique/int_mediation_numerique__structures.sql
- pipeline/dbt/models/staging/sources/france_travail/stg_france_travail__agences.sql
Tout est dans les commits.
Draft pour éviter les déploiements, mais on peut la relire.
> chore(pipeline) : Corriger des coquilles pour la migration Pole Emploi -> France Travail

- pipeline/dbt/models/intermediate/int__geocodages.sql
Adresses can be deleted by the provider, or by us. In both cases, deleting the corresponding geocodages is required to ensure that the relationship between adresses and geocodages stands.
Either that or the relationship test must be downgrade to a warning.
> fix(pipeline): force relation adresses/geocodages

- pipeline/dbt/dbt_project.yml
- pipeline/dbt/macros/domain/checks/check_service.sql
- pipeline/dbt/models/_sources.yml
- pipeline/dbt/models/intermediate/_models.yml
- pipeline/dbt/models/intermediate/int__union_services__enhanced.sql
- pipeline/dbt/models/staging/decoupage_administratif/_decoupage_administratif__models.yml
- pipeline/dbt/models/staging/decoupage_administratif/_decoupage_administratif__sources.yml
- pipeline/dbt/models/staging/decoupage_administratif/stg_decoupage_administratif__epcis.sql
There were cases where we did have the zone_diffusion_code set to "97" which can't be right, as it would mean that a given service coyuld be available across the oceans.
Let's fix it and set the correct, 3-digit department number.
This will also enable their search as we now (since the "new" communes) search for a match agains commune.departement, which can be 3 digits.
I would love to add a data test for this, but not sure how useful that is. So far, CHECK_SERVICE_ERRORS() is only semantic but does not validate for instance that the zone_diffusion_code is a correct department number if the zone_diffusion_type is "department", and so on.
If we wanted to validate this, what should be the correct way to proceed?
> feat(pipeline) : Ensure the zone_diffusion_codes for DROM/COM

- api/cron.json
There is a race condition where the import was started at exactly 30 minutes after every hour, which unfortunately is about exactly the moment when the now hourly `main` DAG exports its parquet files :x
```
[2024-09-25, 08:33:42 UTC] {process_utils.py:194} INFO - uploading data to bucket='data/marts/2024-09-25/scheduled__2024-09-25T07:00:00+00:00/services.parquet'
[2024-09-25, 08:33:49 UTC] {python.py:240} INFO - Done. Returned value was: None
```
Reset it at the first minute of the hour to maximize our chances.
Also, stop doing a difference for staging, as the data there isn't smaller.
> chore(api) : Fix load_inclusion_data import

- pipeline/dbt/models/intermediate/sources/emplois_de_linclusion/int_emplois_de_linclusion__structures.sql
- pipeline/dbt/models/intermediate/sources/mediation_numerique/int_mediation_numerique__structures.sql
We don't want code to stay around forever when clearly it is supposed to be temporary and fixed in the sources.
Remove this as soon as the mednum & les-emplois have fixed the issue.
> chore(pipeline) : Add missing FIXMEs

- pipeline/dbt/models/intermediate/sources/soliguide/int_soliguide__adresses.sql
- pipeline/dbt/models/intermediate/sources/soliguide/int_soliguide__services.sql
`se-presenter` ne devrait pas être défini lorsque l'adresse n'est pas disponible
> chore(soliguide): remove bad se-presenter

- docker-compose.yml
The 'on-failure' setting makes the images restart almost all the time, especially upon reboot, if I work on this project or not.
This is good in a production setting, but in development, restarting after a reboot on my personal computer drains my battery for no good reason.
Furthermore, if there was an actual issue with the containers in development, they should  just stop and the developer should fix the issue, not run into a mindless loop till oblivion.
> chore(dev) : Do not restart docker images in dev

- pipeline/dbt/models/intermediate/int__union_services__enhanced.sql
When the zone_diffusion_code is not filled, the services are not returned.
Following a fix about those zones in
b0c11dddcea7569e6a2acb27249e9a0ee035b703, there was a tiny mistake (an extra 's') that made 50_000 services become undiscoverable.
Since that can become a huge issue, let's enforce better data testing in the pipeline to ensure it does not arise again.
> fix(pipeline) : Fix soliguide,monenfant zone_diffusion issue

- pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
Suite à des modifications du coté de DORA la sous thématique --autre n'est plus remplacée par un null.
Il est donc nécessaire de le faire de notre côté.
@vperron je n'ai pas ajouté les tests car ça presse je le mettrai avec mon autre PR qui corrige les autres erreurs de service
> fix(dora): fix dora service thematics rejected by the quality check 

- pipeline/dbt/models/intermediate/_models.yml
- pipeline/dbt/models/intermediate/int__geocodages.sql
- pipeline/dbt/models/intermediate/int__union_adresses__enhanced.sql
- pipeline/dbt/models/staging/decoupage_administratif/_decoupage_administratif__models.yml
- pipeline/dbt/models/staging/decoupage_administratif/stg_decoupage_administratif__arrondissements.sql
Currently zone_diffusion_code can contain district codes introduced by geocodings. This is a side effect from our previous work on district codes.
This leads to services being only discoverable using the district codes, not city codes.
We can easily make the assumption that, in real life, services are never confined to districts. Therefore we dont want to allow a district zdf type.
This commit replaces district codes by city codes for the zdf.
> fix(pipeline): remove district codes from zdf

- pipeline/dbt/models/intermediate/sources/agefiph/int_agefiph__services.sql
They are referenced by DORA instead.
Before:
```
data-inclusion=# SELECT COUNT(*) FROM public_intermediate.int_agefiph__services ;
count 
-------
27
(1 row)
```
After:
```
data-inclusion=# SELECT COUNT(*) FROM public_intermediate.int_agefiph__services ;
count 
-------
25
(1 row)
```
> chore(pipeline) : Remove two AGEFIPH services

- pipeline/dbt/models/intermediate/_models.yml
- pipeline/dbt/models/intermediate/int__union_contacts.sql
- pipeline/dbt/models/intermediate/int__union_contacts__enhanced.sql
- pipeline/dbt/models/intermediate/int__union_services__enhanced.sql
- pipeline/dbt/models/intermediate/sources/dora/int_dora__contacts.sql
- pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
- pipeline/dbt/models/intermediate/sources/mediation_numerique/int_mediation_numerique__contacts.sql
- pipeline/dbt/models/intermediate/sources/mes_aides/int_mes_aides__contacts.sql
Tickets traités:
- [Bloquer les contacts venant de mes-aides & mediation-numerique apres une opposition Brevo](
https://www.notion.so/dora-beta/Backlog-data-inclusion-2e2a08ce7c7941429f0f80e686e8f6de?p=6e9a4b3d890d41eea898c114ff033fd9&pm=s)
==> celui-ci est généralisé à toute source
- [Ne pas supprimer certaines coordonnées lors d'un hardbounce Brevo](https://www.notion.so/dora-beta/Backlog-data-inclusion-2e2a08ce7c7941429f0f80e686e8f6de?p=103aea89a6e6805ba6aaf4aaa51ffd51&pm=s)
> feat(brevo) : Hide contacts properly for all sources

- pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
Correction des services rejetés par le quality check (erreurs liées aux colonnes `frais` et `modes_orientation_beneficiaire`)
Suite au déploiement en staging
[3 lignes rejetées en staging](https://metabase.data.inclusion.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo2LCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjI5MzR9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)
contre
[1126 lignes rejetées en prod](https://metabase.data.inclusion.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo5LCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjM5NjJ9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)
> fix(dora): fix dora services rejected by the quality check

- pipeline/dbt/models/_sources.yml
- pipeline/dbt/models/intermediate/quality/_quality_models.yml
- pipeline/dbt/snapshots/sources/mes_aides/snps_mes_aides__permis_velo.sql
The stats can't be computed without it, and the snapshot was not computed for the new permis_velo model.
> fix(pipeline) : Fix mes-aides issues with stats & snapshots

- pipeline/RGPD.md
- pipeline/dags/notify_rgpd_contacts.py
- pipeline/dbt/models/intermediate/_models.yml
- pipeline/dbt/models/intermediate/brevo/_brevo__models.yml
- pipeline/dbt/models/intermediate/brevo/int_brevo__contacts.sql
- pipeline/dbt/models/intermediate/int__union_contacts.sql
- pipeline/dbt/models/intermediate/int__union_contacts__enhanced.sql
- pipeline/dbt/models/intermediate/sources/dora/_dora__models.yml
- pipeline/dbt/models/intermediate/sources/dora/int_dora__contacts.sql
- pipeline/dbt/models/intermediate/sources/mediation_numerique/_mediation_numerique_models.yml
- pipeline/dbt/models/intermediate/sources/mediation_numerique/int_mediation_numerique__contacts.sql
- pipeline/dbt/models/intermediate/sources/mes_aides/_mes_aides__models.yml
- pipeline/dbt/models/intermediate/sources/mes_aides/int_mes_aides__contacts.sql
- pipeline/dbt/models/staging/brevo/_brevo__models.yml
- pipeline/dbt/models/staging/brevo/stg_brevo__contacts.sql
After an entire year of operation, we noticed that our sources never change their contact emails. Ever.
Even if someday this happens, we can probably suppose that it's till going to be quite rare.
In those exceptional cases, it means that the structure would get a new RGPD notification.
But it does make the code way easier to maintain and more robust:
- now we will never miss an email that would have been "forgotten" by Brevo (due to rate limits, payment issues, ...)
- it can also be seen as a feature to send a new notification if the email changes, for instance when the previous one was incorrect.
Moreover, we don't need to maintain the `contact_uid` list that was sent to brevo.
> feat(pipeline) : Simplify notify_rgpd_contacts

- api/src/data_inclusion/api/inclusion_data/routes.py
- api/tests/e2e/api/test_inclusion_data.py
Un certain nombre de champs ont été dépréciés mais pas supprimés car toujours en usage chez certains conso.
[On retire la source dans structures car presque pas du tout utilisé en octobre et presque plus utilisé en septembre](https://metabase.data.inclusion.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7ImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiYnJlYWtvdXQiOltbImZpZWxkIiwiY3JlYXRlZF9hdCIseyJiYXNlLXR5cGUiOiJ0eXBlL0RhdGVUaW1lV2l0aExvY2FsVFoiLCJ0ZW1wb3JhbC11bml0IjoibW9udGgifV0sWyJmaWVsZCIsInByb2R1Y3QiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLCJlbmRwb2ludF9uYW1lIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XV0sInNvdXJjZS10YWJsZSI6ImNhcmRfXzI2MiIsImZpbHRlciI6WyJhbmQiLFsidGltZS1pbnRlcnZhbCIsWyJmaWVsZCIsImNyZWF0ZWRfYXQiLHsiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZVdpdGhMb2NhbFRaIn1dLC0zLCJtb250aCIseyJpbmNsd …
> chore(api):remove sources filter on structures

- README.md
Cette branche `special/deploy-main-to-staging` est utilisée en tant que fix temporaire
pour déployer `main` en staging; il suffit de:
* la rebase sur `main`
* s'assurer qu'elle a bien le label `deploy-to-staging`
* lancer un déploiement.
Ceci est un contournement le temps que nous améliorions le système de déploiement de
manière plus générique.
En attendant, prière de laisser la PR ouverte.
> chore(all) : DONOTMERGE, workaround for deploying `main`

- api/tests/e2e/api/test_inclusion_data.py
These two tests 'snapshot' the API response. The response depends on objects (service structures) that are pseudo-randomly generated using factories. In general, it works well: values are generated randomly but deterministically, so when we rerun the tests, the results are reproducible!
However, as soon as we make any changes to the factory or the SQLAlchemy model, the order of value generation shifts, and the values change.
The solution: hard-code the structures/services in these two tests instead of relying on the factory. Credit to vmttn for those explanation
> fix(api): fix flaky tests

- api/src/alembic/env.py
- api/src/alembic/versions/20241203_175736_d5351b394a5e_create_analytics_tables.py
- api/src/alembic/versions/20241205_143006_89e1ece4f56e_migrate_requests_to_analytics.py
- api/src/data_inclusion/api/analytics/models.py
- api/src/data_inclusion/api/analytics/services.py
- api/src/data_inclusion/api/core/db.py
- api/src/data_inclusion/api/inclusion_data/routes.py
- api/src/data_inclusion/api/inclusion_data/services.py
- api/src/data_inclusion/api/inclusion_data/sources.json
- api/src/data_inclusion/api/utils/pagination.py
- api/tests/e2e/api/test_analytics.py
Sur un export du 2 decembre de prod:
  | Nombre d’entree | Date de la plus vieille entree
-- | -- | --
api__consult_service_events | 1336943 | 2023-07-03 21:31:46.365 +0200
api__consult_structure_events | 23120 | 2023-08-01 20:54:31.693 +0200
api__list_services_events | 116636 | 2023-07-03 20:21:19.939 +0200
api__list_structures_events | 122641 | 2023-07-04 10:54:26.028 +0200
api__services_searchs | 74864 | 2024-01-22 14:21:42.841 +0100
`api__consult_service_events` et `api__consult_structure_events` n'ont pas de score_qualite apres migration (normal):
Taux de remplissage pour les colonnes de `api__list_services_events`:
sources_fill_rate | thematiques_fill_rate | departement_fill_rate | region_fill_rate | code_commune_fill_rate | frais_fill_rate | profils_fill_rate | …
> feat(api): add dedicated analytics models

- api/locustfile.py
- api/src/alembic/versions/20250206_145025_45104a7fe9e8_add_score_qualite_and_doublons_to_structures.py
- api/src/alembic/versions/20250206_145025_45104a7fe9e8_add_score_qualite_to_structures.py
- api/src/data_inclusion/api/inclusion_data/commands.py
- api/src/data_inclusion/api/inclusion_data/models.py
- api/src/data_inclusion/api/inclusion_data/routes.py
- api/src/data_inclusion/api/inclusion_data/schemas.py
- api/src/data_inclusion/api/inclusion_data/services.py
- api/tests/e2e/api/__snapshots__/test_inclusion_data.ambr
- api/tests/e2e/api/test_inclusion_commands.py
- api/tests/e2e/api/test_inclusion_data.py
- api/tests/factories.py
Nécessite https://github.com/gip-inclusion/data-inclusion-schema/pull/35 installé (API & DWH)
Le premier commit n'est pas à relire dans cette PR, il reprend les changements de la PR #374 .
Un squash sera nécessaire entre les deux PR (d'une certaine manière !) pour résoudre le souci lié au snapshot OpenAPI qui a fait des siennes dans les deux PR, au moins ici il est traité dans un commit à part pour simplifier la relecture.
> feat(api) : Ajout du paramètre "deduplicate" sur la liste des structures

- api/CONTRIBUTING.md
La documentation manque de précision en ce qui concerne l'utilisation de versions de dev du schéma.
> doc(api): Document how to deploy schema development versions

- api/pyproject.toml
- api/uv.lock
Pas de ticket notion, c'est un fix technique.
* NA J'ai indiqué le ticket notion associé
* NA J'ai passé le ticket notion en review
Je vérifie que la CI passe.
> chore(api): Pin data-inclusion-schema to 0.24.0

- pipeline/dbt/models/intermediate/sources/soliguide/int_soliguide__services.sql
- pipeline/dbt/models/staging/sources/soliguide/_soliguide__models.yml
- pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__services.sql
[Lien vers le ticket notion associé](https://www.notion.so/gip-inclusion/Soliguide-ne-plus-utiliser-le-champ-services_all-name-pour-construire-notre-nom-de-service-1de5f321b6048024b535f31a6864b2c3?pvs=4)
[Dashboard Metabase](https://metabase.data.inclusion.gouv.fr/dashboard/65-valeurs-nom-soliguide)
> fix(pipeline) : Fix soliguide name

- README.md
Cette branche special/deploy-main-to-staging est utilisée en tant que fix temporaire
pour déployer main en staging; il suffit de:
- la rebase sur main
- s'assurer qu'elle a bien le label deploy-to-staging
- lancer un déploiement.
Ceci est un contournement le temps que nous améliorions le système de déploiement de
manière plus générique.
En attendant, prière de laisser la PR ouverte.
Attention à ne pas rebase sur cette PR/ce commit et la merger par erreur.
> chore: DONOTMERGE, workaround for deploying `main`

- pipeline/Dockerfile
There was a glibc version mismatch between the compile and runtime images. It looks like the airflow image uses an outdated glibc version. The image does not get updated as frequently as it used to, now that airflow 3 is out.
Upgrading the package manually may have been enough, but removing the compile image has been favoured as an opportunity to simplify things. Ideally the image customization should be minimal. This would make it easier to deploy airflow somewhere else.
> fix(pipeline): fix airflow image build

- api/pyproject.toml
- api/src/data_inclusion/api/auth/services.py
- api/src/data_inclusion/api/config.py
- api/tests/conftest.py
- api/tests/e2e/api/test_openapi.py
- api/tests/unit/test_auth.py
Thanks to a whitelist, passed as an env var.
Ticket post-mortem.
* NA J'ai réimporté les données marts depuis le datalake
* NA J'emploie le français dans l'interface de l'api (query params, description, etc.)
* NA Si ma PR inclut des modifs de l'orm, j'ai inclus les migrations alembic
* NA J'ai fait une analyse perfs avant/après via locust
> feat(api): Enable allowing old secret's tokens

- pipeline/dbt/models/intermediate/004_finals/_map_publics.sql
[Lien vers le ticket notion associé](https://www.notion.so/champs-li-s-service-publics-2005f321b60480668b7ee05f08c76f69?d=25a5f321b60480509390001c584086c8&source=copy_link#2005f321b6048075b392fc2301c60f6c)
Partout dans le schéma et le code la valeur est `residents-qpv-frr` sauf ici; cela vient initialement du ticket, je pense que par cohérence on devrait tout faire en minuscules. 
> fix(pipeline): typo in publics mapping v1
