- src/data_inclusion/api/entrypoints/fastapi.py
- tests/inclusion/conftest.py
- tests/inclusion/factories.py
- tests/inclusion/test_api.py
> feat(api): filter services by source

- pipeline/dbt/models/intermediate/mediation_numerique/int_mediation_numerique__services.sql
- pipeline/dbt/models/sources/mediation_numerique/stg_mediation_numerique__services.sql
> fix(mednum): use prise_rdv

- CONTRIBUTING.md
- docker-compose.yml
- pipeline/CONTRIBUTING.md
Assure la compatibilité avec la v2 de docker-compose
> Update docker compose for v2

- pipeline/dbt/models/intermediate/soliguide/int_soliguide__services.sql
Ajout de mapping pour les thématiques/catégories de Soliguide.
Basé sur [notre document de mapping](https://docs.google.com/spreadsheets/d/1PtQ0_JRhHr37Ftjdjuv97FlHqZYWnmneOlDroi-4WhA/edit#gid=951099216).
> feat(pipeline): soliguide: more category mapping

- api/src/alembic/versions/2daaedf28c12_extended_request.py
- api/src/data_inclusion/api/core/auth.py
- api/src/data_inclusion/api/core/request/models.py
- api/src/data_inclusion/api/core/request/services.py
- api/src/data_inclusion/api/entrypoints/fastapi.py
- api/tests/core/test_request.py
Add:
* query parameters
* path parameters
* endpoint name
Refactor middleware to use starlette's auth api.
> feat(api): log requests parameters

- pipeline/Dockerfile
After having tried to reproduce a few issues that happen in staging, I think it will make the debug process much easier to be able to modify the scheduler files (for instance to add debug prints) so that the data investigation gets easier.
> feat(pipeline) : Add vim in the image

- pipeline/defaults.env
Après vérification et suppression de mes volumes, j'avais dû m'emmêler les pinceaux: ça ne pose pas de problèmes à d'autres DAGs que, de manière attendue, à ceux de l'AGEFIPH et de Monenfant. Mais bon c'est déjà ça de pris...
> fix(pipeline) : Add missing values in defaults.env

- CONTRIBUTING.md
- api/setup.py
- api/src/data_inclusion/api/entrypoints/fastapi.py
- deployment/docker-compose.yml
- pipeline/setup.py
> chore(all) : Transfer code ownership to gip-inclusion org

- pipeline/dbt/models/staging/sources/dora/_dora__models.yml
Suite à https://github.com/gip-inclusion/dora-back/pull/192
> fix(dora): accept zone_diffusion_type pays

- pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
CF https://www.notion.so/dora-beta/Afficher-les-donn-es-de-contacts-dans-l-API-a7aa0e9aacee4078910a643583b7a9d4?pvs=4
> feat(pipeline) : Expose Dora contact information when possible

- api/src/data_inclusion/api/entrypoints/fastapi.py
- pipeline/dbt/models/marts/api/api_service.sql
The API starts to be too slow.
> feat(api,pipeline) : Add an index on the thematiques

- api/requirements/dev-requirements.txt
- api/requirements/requirements.txt
- api/requirements/test-requirements.txt
- api/setup.py
- api/src/data_inclusion/api/entrypoints/fastapi.py
- pipeline/dbt/models/intermediate/sources/france_travail/int_france_travail__agences.sql
- pipeline/dbt/seeds/schema/typologies_de_structures.csv
Gestion des contacts et de la typologie.
> FT : Petits correctifs

- api/src/data_inclusion/api/entrypoints/fastapi.py
- pipeline/dbt/models/intermediate/sources/agefiph/int_agefiph__services.sql
The AGEFIPH wants us to specifically target the service offers related to people with disabilities only.
> feat(pipeline) : Remove unwanted AGEFIPH services

- api/src/data_inclusion/api/entrypoints/fastapi.py
- api/tests/inclusion/test_api.py
> feat(api) : Return services that are less than 50km away

- pipeline/dbt/models/intermediate/sources/mes_aides/int_mes_aides__adresses.sql
- pipeline/dbt/models/intermediate/sources/mes_aides/int_mes_aides__structures.sql
- pipeline/dbt/models/marts/api/api_service.sql
- pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__garages.sql
Elles n'ont jamais fonctionné, pour cause de typo.
Ajoute une ultime optimisation en DB.
> feat(pipeline) : Fix the mes_aides.garages structures

- .vscode/extensions.json
- api/.flake8
- api/.vscode/settings.json
- pipeline/.flake8
> chore: clean up flake8 conf files

- pipeline/dags/notify_rgpd_contacts.py
An import was broken and forgotten.
> fixup(pipeline) : Fix notify RGPD contacts

- api/sources.json
- api/src/alembic/versions/0c9e8a379aa6_add_sources_table_relations.py
- api/src/data_inclusion/api/core/db.py
- api/src/data_inclusion/api/core/request/middleware.py
- api/src/data_inclusion/api/core/request/services.py
- api/src/data_inclusion/api/entrypoints/cli.py
- api/src/data_inclusion/api/entrypoints/fastapi.py
- api/src/data_inclusion/api/models.py
- api/src/data_inclusion/api/schema.py
- api/tests/conftest.py
- api/tests/core/test_request.py
- api/tests/inclusion/conftest.py
- api/tests/inclusion/factories.py
- api/tests/inclusion/test_api.py
First example
```
[
...
{
"slug": "france-travail",
"nom": "France travail",
"description": "France travail est un site internet qui permet de trouver des offres d’emploi.",
"nb_services": 20447,
"nb_structures": 889
},
{
"slug": "mediation-numerique",
"nom": "Cartographie numérique",
"description": "lorem",
"nb_services": 16390,
"nb_structures": 16390
},
{
"slug": "dora",
"nom": "DORA",
"description": "DORA est un outil de recherche d’offres de logement social en France.",
"nb_services": 8870,
"nb_structures": 6832
},
...
]
```
> feat(api,pipeline) : Améliorer l'endpoint de sources

- api/requirements/test-requirements.txt
- api/setup.py
- api/src/data_inclusion/api/core/request/services.py
Down depuis le 4 Mars suite à une refonte.
Il manquait une toute petite chose.
> fix(api) : Restaurer les requetes ApiRequest

- .pre-commit-config.yaml
- api/requirements/dev-requirements.txt
- api/requirements/requirements.txt
- api/requirements/test-requirements.txt
- api/setup.py
- api/src/data_inclusion/api/inclusion_data/routes.py
- api/tests/e2e/api/test_inclusion_data.py
Related to https://github.com/gip-inclusion/les-emplois/pull/3755/files
> feat: add service redirect endpoint

- pipeline/defaults.env
Before switching to the new API.
> chore(pipeline) : Update CD35 file URL

- datawarehouse/Dockerfile
- pipeline/dbt/dbt_project.yml
- pipeline/dbt/models/staging/sources/reseau_alpha/stg_reseau_alpha__formations.sql
- pipeline/dbt/models/staging/sources/reseau_alpha/stg_reseau_alpha__structures.sql
Pour l'exemple, ce qu'on peut faire en ayant la main sur le serveur où tourne pg.
> refactor: parse dates with french locale

- pipeline/dags/dag_utils/geocoding.py
- pipeline/dags/main.py
- pipeline/dbt/models/intermediate/sources/reseau_alpha/int_reseau_alpha__adresses.sql
- pipeline/dbt/models/staging/sources/cd72/stg_cd72__services.sql
- pipeline/dbt/models/staging/sources/cd72/stg_cd72__structures.sql
- pipeline/dbt/models/staging/sources/reseau_alpha/stg_reseau_alpha__structures.sql
- pipeline/tests/integration/test_geocoding.py
Dans l'objectif d'avoir des adresses les plus fiables possibles et s'ouvrir la possibilité de les normaliser.
> Améliorer le géocodage de nos adresses

- api/src/alembic/versions/20240820_115237_517603187775_cleanup_unused_fields.py
- api/src/data_inclusion/api/inclusion_data/commands.py
Par ailleurs, j'ai demandé au support Scalingo s'ils avaient une solution native pour qu'on ait une alerte en cas de cron échoué, pas de réponse pour l'instant.
Au pire il faudra faire notre propre surcouche (pour envoyer sur un webhook Mattermost par exemple) ou en instrumentant Sentry dans `commands.py`; actuellement il ne surveille que l'app.
> chore(api) : Fix the import command and migrations

- pipeline/dags/compute_hourly.py
- pipeline/dags/dag_utils/notifications.py
- pipeline/dags/import_brevo.py
- pipeline/dags/import_data_inclusion_api.py
- pipeline/dags/import_monenfant.py
- pipeline/dags/import_sources.py
- pipeline/dags/main.py
- pipeline/dags/notify_rgpd_contacts.py
It was some repeated code for no good reason.
> chore(pipeline) : Create a common Mattermost notifier

- pipeline/dbt/models/staging/sources/mediation_numerique/stg_mediation_numerique__structures.sql
Maintenant, 2 commits assez indépendants dans la PR, mais ça corrige pas mal de choses.
> chore(pipeline) : remove sub-labs from mednum

- datawarehouse/processings/pyproject.toml
- datawarehouse/processings/requirements/dev-requirements.txt
- datawarehouse/processings/requirements/requirements.txt
- datawarehouse/processings/requirements/test-requirements.txt
- pipeline/dags/import_data_inclusion_api.py
- pipeline/requirements/dev/requirements.txt
- pipeline/requirements/tasks/python/requirements.in
- pipeline/requirements/tasks/python/requirements.txt
For an unknown reason, sometimes the `pg_dump` fails to finish.
Let's add a few retries.
Result:
```
[2024-10-23, 07:14:12 UTC] {process_utils.py:194} INFO - Tunnel created
[2024-10-23, 07:14:13 UTC] {process_utils.py:194} INFO - ('pg_dump postgresql://airflaw:ko8B-xxxxxxx@127.0.0.1:33657/data_inclus_1511?sslmode=prefer --format=custom --clean --if-exists --no-owner --no-privileges --table api__requests --table api__communes --table api__services --table api__structures --file /tmp/tmpxjt25_ta',)
[2024-10-23, 07:14:13 UTC] {process_utils.py:194} INFO - b''
[2024-10-23, 07:14:13 UTC] {process_utils.py:194} INFO - b'pg_dump: error: connection to server at "127.0.0.1", port 33657 failed: FATAL:  password authentication failed for user "airflaw"\nconnection to server at "127.0.0.1", port …
```
> chore(pipeline) : Attempt at fixing the API import

- pipeline/dags/dag_utils/sources/soliguide.py
- Adaptation à la nouvelle méthode de gestion des appels API de Soliguide.
- Implémentation de la pagination manuelle en fonction du nombre d'éléments reçus dans chaque réponse.
> fix(soliguide): handle page number during call to soliguide api

- datawarehouse/processings/requirements/dev-requirements.txt
- datawarehouse/processings/requirements/requirements.txt
- datawarehouse/processings/requirements/test-requirements.txt
afin d'arrondir le score de qualité
> chore(pipeline): bump data-inclusion-schema

- pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__lieux.sql
- pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__phones.sql
- pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__services.sql
https://www.notion.so/gip-inclusion/24610bd08f8a412c83c09f6b36a1a44f?v=34cdd4c049e44f49aec060657c72c9b0&p=1435f321b60480a589b3fc2b439cebdb&pm=s
https://www.notion.so/gip-inclusion/24610bd08f8a412c83c09f6b36a1a44f?v=34cdd4c049e44f49aec060657c72c9b0&p=13c5f321b60480f4bef4d89d1d36eb5e&pm=s
> fix(pipeline) : Fix soliguide prices detail and ignore dora structures

- api/src/alembic/versions/20241205_143006_89e1ece4f56e_migrate_requests_to_analytics.py
> fix(api): migrate search without lat/lon

- pipeline/dbt/models/intermediate/sources/agefiph/int_agefiph__services.sql
https://www.notion.so/gip-inclusion/24610bd08f8a412c83c09f6b36a1a44f?v=34cdd4c049e44f49aec060657c72c9b0&p=1915f321b60480a3a8e5ed0b1031eb55&pm=s
> fix(agefiph): add mapping thematique

- api/src/data_inclusion/api/app.py
- api/tests/e2e/api/test_auth.py
Will probably help with disallowing some incoming traffic
> chore(api) : Add a robots.txt policy

- pipeline/dbt/models/intermediate/quality/_quality_models.yml
There is a missing value in stream 'offres' coresponding to one source mission_local.
> fix(quality): fix quality test

- api/src/alembic/versions/20250116_160438_a06b6f7d1cbe_structures_add_cluster_id.py
- api/src/data_inclusion/api/inclusion_data/models.py
- api/src/data_inclusion/api/inclusion_data/routes.py
- api/src/data_inclusion/api/inclusion_data/schemas.py
- api/src/data_inclusion/api/inclusion_data/services.py
- api/tests/e2e/api/__snapshots__/test_inclusion_data.ambr
- api/tests/e2e/api/test_inclusion_data.py
- pipeline/dbt/models/marts/inclusion/_inclusion_models.yml
- pipeline/dbt/models/marts/inclusion/marts_inclusion__structures.sql
Prêt à relire il me semble, j'ai simplement une interrogation sur la génération OpenAPI dans le test.
> feat(api) : Return structure duplicates in list & retrieve

- api/CONTRIBUTING.md
- api/locustfile.py
- api/requirements/test-requirements.txt
- api/setup.py
- api/src/data_inclusion/api/inclusion_data/commands.py
- api/src/data_inclusion/api/inclusion_data/services.py
- api/tests/e2e/api/test_inclusion_data.py
étant donné qu'on ne fait qu'une insertion en batch toutes les heures, et que les données restent stables entre 2 batchs, la pagination n'est pas affectée
j'ai introduit un fichier `./api/locustfile.py` pour faire des petits benchmark en se rapprochant des conditions réelles d'utilisation
**avant en local**
```
Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET      /api/v0/services/?page=[  0] …
```
> perf(api): insert data sorted and drop order by

- api/src/data_inclusion/api/app.py
- api/src/data_inclusion/api/config.py
Plutôt un point remonté par Charles, mais ça prend très peu de code et de temps, donc...
(note: il faudra editer les vars d'env dans scalingo:
prod="api.data.inclusion.gouv.fr,api.data.inclusion.beta.gouv.fr,data-inclusion-api-prod.osc-secnum-fr1.scalingo.io"
staging="api-staging.data.inclusion.gouv.fr,api-staging.data.inclusion.beta.gouv.fr,data-inclusion-api-staging.osc-secnum-fr1.scalingo.io" )
> chore(api) : Add a check on the allowed hosts

- api/src/data_inclusion/api/decoupage_administratif/commands.py
> fix(api): remove zero region code to match commune database

- api/.template.env
> chore(api): set allowed hosts for dev

- api/src/data_inclusion/api/config.py
[Lien vers le ticket notion associé](https://www.notion.so/gip-inclusion/24610bd08f8a412c83c09f6b36a1a44f?v=34cdd4c049e44f49aec060657c72c9b0&p=19e5f321b604805f9c4fd601dc0a2a0d&pm=s)
~~si ma PR concerne la **pipeline**, le **datawarehouse** ou la **deduplication**~~
~~* [ ] J'ai actualisé les données liées à ma PR (avec une extraction récente)~~
~~* [ ] J'ai utilisé un dump récent de la prod~~
~~* [ ] J'ai exécuté en local les modèles (via `dbt build -s models/...` ou airflow en local)~~
~~* [ ] J'ai déployé en staging et exécuté les dags~~
~~* [ ] J'ai indiqué quelques questions metabase pour mettre en évidence l'impact de …
> fix(api): correct url db to avoid failure during start up

- api/requirements/dev-requirements.txt
- api/requirements/requirements.txt
- api/requirements/test-requirements.txt
- api/setup.py
- api/src/data_inclusion/api/analytics/services.py
- api/src/data_inclusion/api/inclusion_data/routes.py
- api/src/data_inclusion/api/inclusion_data/services.py
- api/src/data_inclusion/api/inclusion_schema/routes.py
- api/tests/e2e/api/__snapshots__/test_inclusion_data.ambr
- api/tests/e2e/api/test_inclusion_data.py
- api/tests/factories.py
- datawarehouse/Dockerfile
- datawarehouse/processings/pyproject.toml
- datawarehouse/processings/requirements/dev-requirements.txt
- datawarehouse/processings/requirements/requirements.txt
- datawarehouse/processings/requirements/test-requirements.txt
[Ticket Notion associé](https://www.notion.so/gip-inclusion/volution-des-crit-res-du-score-de-qualit-18a5f321b6048038936ac4d640cf392e?pvs=4)
Les [questions Metabase](https://metabase.data.inclusion.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo2LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjI3MTZ9fSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)  ont été analysées par Antoine dans la version de dev.
En attente du merge de https://github.com/gip-inclusion/data-inclusion-schema/pull/42 pour le commit en __wip.
Je redéploierai en staging malgré tout.
si ma PR concerne la **pipeline**, le …
> chore: deploy schema v0.21.0

- pipeline/defaults.env
[Lien vers le ticket notion associé](https://gip-inclusion.slack.com/archives/C088XSD8VNV/p1741215894840179?thread_ts=1739287263.731819&cid=C088XSD8VNV)
> fix(pipeline): change url gsheet for FT

- api/locustfile.py
- api/src/alembic/versions/20250305_091252_9c7df6028d95_add_cluster_best_duplicate.py
- api/src/data_inclusion/api/inclusion_data/commands.py
- api/src/data_inclusion/api/inclusion_data/models.py
- api/src/data_inclusion/api/inclusion_data/routes.py
- api/src/data_inclusion/api/inclusion_data/schemas.py
- api/src/data_inclusion/api/inclusion_data/services.py
- api/tests/e2e/api/__snapshots__/test_inclusion_data.ambr
- api/tests/e2e/api/test_inclusion_commands.py
- api/tests/e2e/api/test_inclusion_data.py
- api/tests/factories.py
[Lien vers le ticket notion associé](https://www.notion.so/gip-inclusion/Mise-en-place-de-la-d-duplication-de-structures-dans-les-routes-services-19f5f321b604808f8a84efe107a4d0f1?pvs=4)
```
Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET …
```
> feat(api): Add deduplication in search/services, fix other service routes

- api/src/data_inclusion/api/inclusion_data/routes.py
> doc(api): Add links to dedup/score articles

- datawarehouse/Dockerfile
> fix(datawarehouse): change lang in dockerfile

- api/src/data_inclusion/api/inclusion_data/sources.json
> feat(api): add source carif oref

- api/src/alembic/versions/20250312_171949_7a475b0386a1_add_new_filter_to_analytics_events.py
- api/src/data_inclusion/api/analytics/models.py
- api/src/data_inclusion/api/analytics/services.py
- api/src/data_inclusion/api/inclusion_data/routes.py
- api/tests/e2e/api/test_analytics.py
[Lien vers le ticket notion associé](https://www.notion.so/gip-inclusion/24610bd08f8a412c83c09f6b36a1a44f?v=34cdd4c049e44f49aec060657c72c9b0&p=1b25f321b60480ce820cfc7227a9538a&pm=s)
> feat(api): add filters to analytics events

- pipeline/dbt/models/intermediate/quality/int_quality__stats.sql
- pipeline/dbt/models/staging/sources/carif_oref/_carif_oref__sources.yml
[Lien vers le ticket notion associé](https://airflow.prod.data.inclusion.gouv.fr/dags/import_data_inclusion_api/grid?dag_run_id=scheduled__2025-03-17T07%3A15%3A00%2B00%3A00&task_id=generate_source_stats&tab=logs)
> fix(pipeline): fix quality stats for carif oref

- .pre-commit-config.yaml
- deployment/.terraform.lock.hcl
- deployment/.tool-versions
- deployment/main.tf
- deployment/provider.tf
> chore(deployment): add consumers to bucket policy

- pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__services.sql
> fix(pipeline): clean soliguide service names

- pipeline/dbt/models/intermediate/sources/carif_oref/int_carif_oref__services.sql
[Lien vers le ticket notion associé](https://www.notion.so/gip-inclusion/Source-carif-oref-de-nombreux-services-sans-zone-diff-code-donc-introuvable-sur-DORA-1ce5f321b60480d9a587d3af63b2687a)
> chore(carif_oref): set code when region perimeter

- pipeline/dags/probe_api.py
[Lien vers le ticket notion associé](https://airflow.prod.data.inclusion.gouv.fr/dags/probe_api/grid?dag_run_id=scheduled__2025-04-13T07%3A00%3A00%2B00%3A00&task_id=compare_results&tab=logs)
~* [ ] J'ai indiqué le ticket notion associé~
~* [ ] J'ai passé le ticket notion en review~
~* [ ] J'ai actualisé les données liées à ma PR (avec une extraction récente)~
~* [ ] J'ai utilisé un dump récent de la prod~
~* [ ] J'ai exécuté en local les modèles (via `dbt build -s models/...` ou airflow en local)~
~* [ ] J'ai indiqué quelques questions metabase …
> fix(pipeline): improve error management for probe dags

- api/tests/e2e/api/__snapshots__/test_inclusion_data.ambr
> fix(api): fix tests snapshot

- pipeline/dbt/models/staging/sources/soliguide/_soliguide__models.yml
- pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__categories.sql
> fix(soliguide): deal with new categories

- pipeline/dbt/models/intermediate/_models.yml
- pipeline/dbt/models/intermediate/int__union_contacts__enhanced.sql
- pipeline/dbt/models/intermediate/int__union_services__enhanced.sql
> fix(pipeline): fix enhanced contact filter conditions

- pipeline/dbt/macros/domain/checks/check_common.sql
> fix(pipeline): fix udf check url if data is None

- datawarehouse/processings/src/data_inclusion/processings/deduplicate.py
[Lien vers le ticket notion associé](https://www.notion.so/gip-inclusion/Rajouter-la-source-cd35-dans-le-syst-me-de-d-duplication-1995f321b604805a98d7cec84134200f?pvs=4)
**TODO**
> chore(datawarehouse) : Add cd35 to the list of possible duplicates

- api/CONTRIBUTING.md
- api/entrypoint.sh
- api/src/data_inclusion/api/app.py
- api/src/data_inclusion/api/config.py
- api/src/data_inclusion/api/utils/cursor_pagination.py
[Lien vers le ticket notion associé](https://www.notion.so/gip-inclusion/Am-liorer-les-perfs-en-v1-20d5f321b604809b83b5d85ce951bf6e?v=34cdd4c049e44f49aec060657c72c9b0&source=copy_link)
* NA J'emploie le français dans l'interface de l'api (query params, description, etc.)
* NA Si ma PR inclut des modifs de l'orm, j'ai inclus les migrations alembic
* NA J'ai ajouté des tests
> feat(api): add compression and increase page size
